/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestordecitasmedicas.pantallas;

import entidades.Cita;
import entidades.Especialidad;
import entidades.Medico;
import entidades.Paciente;

import gestordecitasmedicas.GestorDeCitasMedicas;
import javax.swing.JFrame;

/**
 *
 * @author Estudiante
 */
public class JRFrameCita extends javax.swing.JFrame {

    private JRFrameGestCita padre;
    
    private Cita cita;
    private boolean estoyEditando = false;

    private Medico MedicoSeleccionado;
    private Paciente pacienteSeleccionado;
    private Especialidad EspecialidadSeleccionada;
    
    
    /**
     * Creates new form JRFrameCita
     */
    public JRFrameCita(JRFrameGestCita padre) {
        initComponents();
        this.padre = padre;

        cb_especialidad.removeAllItems();
        cb_especialidad.setEnabled(false);
        
        cb_hora.removeAllItems();
        for (String hora: GestorDeCitasMedicas.horasDisponibles) {
            cb_hora.addItem(hora);
        }
        
        cb_fecha.removeAllItems();
        for (String fecha: GestorDeCitasMedicas.fechasDisponibles) {
            cb_fecha.addItem(fecha);
        }     
    }
    
    public JRFrameCita(JRFrameGestCita padre, Cita cita) {
        initComponents();
        this.padre = padre;
        this.cita = cita;
        this.estoyEditando = true;
        this.btn_buscarPac.setVisible(false);
        this.btn_buscarMed.setVisible(false);
        this.btn_guardar.setVisible(false);
        lblTitulo.setText("Visualizar Cita");
        this.txtMedico.setText(cita.getMedico().getDatosMostrar());
        this.txtPaciente.setText(cita.getPaciente().getDatosMostrar());
        cb_especialidad.removeAllItems();
        cb_especialidad.addItem(cita.getEspecialidad().getNombre());
        cb_fecha.removeAllItems();
        cb_fecha.addItem(GestorDeCitasMedicas.fechasDisponibles.get(cita.getFecha()));
        cb_hora.removeAllItems();
        cb_hora.addItem(GestorDeCitasMedicas.horasDisponibles.get(cita.getHora()));
        
        
    }
    
    
    
    /**
    JRFrameCita(JRFrameGestCita aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }    
    /
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        txtMedico = new javax.swing.JTextField();
        btn_buscarPac = new javax.swing.JButton();
        btn_buscarMed = new javax.swing.JButton();
        cb_especialidad = new javax.swing.JComboBox<>();
        cb_fecha = new javax.swing.JComboBox<>();
        cb_hora = new javax.swing.JComboBox<>();
        btn_guardar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("Nueva Cita");

        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });

        btn_buscarPac.setText("Buscar Paciente");
        btn_buscarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarPacActionPerformed(evt);
            }
        });

        btn_buscarMed.setText("Buscar Medico");
        btn_buscarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarMedActionPerformed(evt);
            }
        });

        cb_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_especialidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_especialidadPropertyChange(evt);
            }
        });

        cb_fecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPaciente)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMedico)
                                    .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_especialidad, 0, 243, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_buscarMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_buscarPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_guardar)))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarPac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscarMed)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salir)
                    .addComponent(btn_guardar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    
    public void guardarCita(){
        if (MedicoSeleccionado != null && pacienteSeleccionado != null) {
            EspecialidadSeleccionada = MedicoSeleccionado.getEspecialidades().get(cb_especialidad.getSelectedIndex());
            cita.setFecha(cb_fecha.getSelectedIndex());
            cita.setHora(cb_hora.getSelectedIndex());
            cita = new Cita(MedicoSeleccionado,pacienteSeleccionado,EspecialidadSeleccionada);
            this.padre.agregarCita(cita);
        }                    
    }
    
    public void setPaciente(Paciente paciente){ //Encapsular datos
        this.pacienteSeleccionado = paciente;
        txtPaciente.setText(paciente.getDatosMostrar());
    }
    
    public void setMedico(Medico medico){
        this.MedicoSeleccionado = medico;
        txtMedico.setText(this.MedicoSeleccionado.getDatosMostrar());
        
        cb_especialidad.removeAllItems();
        for (Especialidad espec: medico.getEspecialidades()) {
            cb_especialidad.addItem(espec.getNombre());         
        }
        
        cb_especialidad.setEnabled(true);
    }
    
    
    private void btn_buscarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarMedActionPerformed
        
        JRFrameMedicos pantallaMedicos = new JRFrameMedicos(this);
        pantallaMedicos.setLocationRelativeTo(this);
        pantallaMedicos.setVisible(true);
        this.setVisible(false);      
    }//GEN-LAST:event_btn_buscarMedActionPerformed
    
    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        guardarCita();
        Salir();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void btn_buscarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarPacActionPerformed
        
        JRFramePaciente pantallaPacientes = new JRFramePaciente(this);
        pantallaPacientes.setLocationRelativeTo(this);
        pantallaPacientes.setVisible(true);
        this.setVisible(false);   
    }//GEN-LAST:event_btn_buscarPacActionPerformed

    private void cb_especialidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_especialidadPropertyChange
        
        if (this.MedicoSeleccionado!=null) {
            Especialidad espec = this.MedicoSeleccionado.getEspecialidades().get(cb_especialidad.getSelectedIndex());
            EspecialidadSeleccionada = espec;
        }      
    }//GEN-LAST:event_cb_especialidadPropertyChange

    
    
    
    private void Salir(){
        padre.setVisible(true); //Muestra la ventana padre   
        this.dispose();//Elimina esta ventana para no ocupar espacio en la memoria
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JRFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JRFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JRFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JRFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JRFrameCita(new JRFrameGestCita()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_buscarMed;
    private javax.swing.JButton btn_buscarPac;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cb_especialidad;
    private javax.swing.JComboBox<String> cb_fecha;
    private javax.swing.JComboBox<String> cb_hora;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
